### ISSUE TITLE
Crear serializador para mapeo de atributos

### ISSUE THREAD

**Issue by TheRustifyer** [gbm25/Custom-discord-bot#3]
- Se debe de crear un serializador que traduzca a JSON los valores que contiene el objeto `GenshinImpact` para poder completar la refactorización del método `scrap_codes` de la clase `GenshinImpact`

**Comment by gbm25** [comment]
Se ha creado el pull request #5 para subsanar este problema y todos los cambios derivados de el.

Realice un par de tests para comprobar que todo funciona, pero es necesario un testeo más prolongado, lo subiré al servidor de prueba mañana a primera hora y si tras 48 horas no veo errores, completare el pull request.

**Comment by TheRustifyer** [comment]
Está cerrado entonces este PR?

**Comment by gbm25** [comment]
Estoy revisando los logs por si veo algo raro, pero parece todo correcto, voy a proceder a realizar el merge del Pull Request.
