### ISSUE TITLE
La expresión file.close() es innecesaria

### ISSUE THREAD

**Issue by TheRustifyer** [gbm25/Custom-discord-bot#7]
En Python3, la expresión `with` se encarga de cerrar automáticamente todos los flujos de datos y buffers que se abren con ella misma.

En la línea 15, el `file.close()` no tiene efecto.

**Comment by gbm25** [comment]
Se ha corregido en el commit 3e952512ab0f59722f4b92e0bc438ee6991dbf15 junto a otros cambios en el archivo.
El pull request a master aún va a tardar, puesto que no es un error que afecte al correcto funcionamiento del bot, y se puede esperar a incluir junto a las nuevas funcionalidades una vez se hayan probado.
